"""catalog.py — the full set of companies this engine can scrape.

This is the "menu" the onboarding wizard shows. Each entry carries just
enough plumbing (kind + slug + any ATS-specific extras like `board`,
`search_url`, `link_re`, `wait_selector`, `host`, `domain`, `urls`,
`origin`, `display_name`, `categories`) for the wizard to generate a
valid SOURCES entry in data/user_config.py.

User-tunable fields (`queries`) are intentionally NOT here — those are
personal and belong in data/user_config.py only.

Generated from data/user_config.py; see tooling/build_catalog.py if we
ever want a repeatable rebuild. For now, hand-maintained + re-run the
extraction when adding a new company.
"""

CATALOG = [{'name': 'AMI', 'kind': 'ashby', 'slug': 'ami', 'group': 'AI Startups'},
 {'name': 'Anyscale', 'kind': 'ashby', 'slug': 'anyscale', 'group': 'AI Startups'},
 {'name': 'AssemblyAI', 'kind': 'greenhouse', 'slug': 'assemblyai', 'group': 'AI Startups'},
 {'name': 'Baseten', 'kind': 'ashby', 'slug': 'baseten', 'group': 'AI Startups'},
 {'name': 'Black Forest Labs',
  'kind': 'pw',
  'slug': 'blackforestlabs',
  'board': 'https://bfl.ai/careers',
  'search_url': 'https://bfl.ai/careers',
  'link_re': 'href="(https?://[^"]*greenhouse[^"]*/blackforestlabs[^"]*|/careers/[^"#?/]+/?)"',
  'origin': 'https://bfl.ai',
  'wait_selector': "a[href*='greenhouse'], a[href*='/careers/']",
  'group': 'AI Startups'},
 {'name': 'Braintrust', 'kind': 'ashby', 'slug': 'braintrust', 'group': 'AI Startups'},
 {'name': 'Cerebras', 'kind': 'ashby', 'slug': 'cerebras', 'group': 'AI Startups'},
 {'name': 'Character AI', 'kind': 'ashby', 'slug': 'character', 'group': 'AI Startups'},
 {'name': 'Cline', 'kind': 'greenhouse', 'slug': 'cline', 'group': 'AI Startups'},
 {'name': 'Cognition',
  'kind': 'ashby',
  'slug': 'cognition',
  'board': 'https://cognition.com/careers',
  'group': 'AI Startups'},
 {'name': 'Coreweave', 'kind': 'greenhouse', 'slug': 'coreweave', 'group': 'AI Startups'},
 {'name': 'Crusoe', 'kind': 'ashby', 'slug': 'crusoe', 'group': 'AI Startups'},
 {'name': 'Deepgram', 'kind': 'ashby', 'slug': 'deepgram', 'group': 'AI Startups'},
 {'name': 'Etched', 'kind': 'ashby', 'slug': 'etched', 'group': 'AI Startups'},
 {'name': 'Fireworks AI', 'kind': 'ashby', 'slug': 'fireworks', 'group': 'AI Startups'},
 {'name': 'H', 'kind': 'ashby', 'slug': 'hcompany', 'group': 'AI Startups'},
 {'name': 'Imbue', 'kind': 'greenhouse', 'slug': 'imbue', 'group': 'AI Startups'},
 {'name': 'Lambda', 'kind': 'ashby', 'slug': 'lambda', 'group': 'AI Startups'},
 {'name': 'LangChain', 'kind': 'ashby', 'slug': 'langchain', 'group': 'AI Startups'},
 {'name': 'Lightning AI', 'kind': 'greenhouse', 'slug': 'lightningai', 'group': 'AI Startups'},
 {'name': 'LlamaIndex', 'kind': 'ashby', 'slug': 'llamaindex', 'group': 'AI Startups'},
 {'name': 'MatX', 'kind': 'ashby', 'slug': 'matx', 'group': 'AI Startups'},
 {'name': 'Modal', 'kind': 'ashby', 'slug': 'modal', 'group': 'AI Startups'},
 {'name': 'Nebius', 'kind': 'greenhouse', 'slug': 'nebius', 'group': 'AI Startups'},
 {'name': 'Nomic', 'kind': 'ashby', 'slug': 'nomic', 'group': 'AI Startups'},
 {'name': 'Observe AI', 'kind': 'greenhouse', 'slug': 'observeai', 'group': 'AI Startups'},
 {'name': 'Perplexity', 'kind': 'ashby', 'slug': 'perplexity', 'group': 'AI Startups'},
 {'name': 'Physical Intelligence', 'kind': 'ashby', 'slug': 'physicalintelligence', 'group': 'AI Startups'},
 {'name': 'Pika', 'kind': 'ashby', 'slug': 'pika', 'group': 'AI Startups'},
 {'name': 'Pinecone', 'kind': 'ashby', 'slug': 'pinecone', 'group': 'AI Startups'},
 {'name': 'Poolside', 'kind': 'ashby', 'slug': 'poolside', 'group': 'AI Startups'},
 {'name': 'Prime Intellect', 'kind': 'ashby', 'slug': 'primeintellect', 'group': 'AI Startups'},
 {'name': 'Rain', 'kind': 'ashby', 'slug': 'rain', 'group': 'AI Startups'},
 {'name': 'Reka', 'kind': 'ashby', 'slug': 'reka', 'group': 'AI Startups'},
 {'name': 'Replit', 'kind': 'ashby', 'slug': 'replit', 'group': 'AI Startups'},
 {'name': 'Rewind AI', 'kind': 'ashby', 'slug': 'rewind', 'group': 'AI Startups'},
 {'name': 'Runway', 'kind': 'ashby', 'slug': 'runway', 'group': 'AI Startups'},
 {'name': 'Sakana AI', 'kind': 'workable', 'slug': 'sakana-ai', 'group': 'AI Startups'},
 {'name': 'SSI', 'kind': 'ashby', 'slug': 'ssi', 'group': 'AI Startups'},
 {'name': 'Tenstorrent', 'kind': 'greenhouse', 'slug': 'tenstorrent', 'group': 'AI Startups'},
 {'name': 'Thinking Machines', 'kind': 'ashby', 'slug': 'ThinkingMachines', 'group': 'AI Startups'},
 {'name': 'Together AI', 'kind': 'greenhouse', 'slug': 'togetherai', 'group': 'AI Startups'},
 {'name': 'Voyage AI', 'kind': 'workable', 'slug': 'voyage', 'group': 'AI Startups'},
 {'name': 'Weaviate', 'kind': 'ashby', 'slug': 'weaviate', 'group': 'AI Startups'},
 {'name': 'Zed', 'kind': 'ashby', 'slug': 'zed', 'group': 'AI Startups'},
 {'name': 'Adobe',
  'kind': 'workday',
  'slug': 'adobe',
  'board': 'https://adobe.wd5.myworkdayjobs.com/external_experienced',
  'group': 'Big Tech'},
 {'name': 'Airbnb', 'kind': 'greenhouse', 'slug': 'airbnb', 'group': 'Big Tech'},
 {'name': 'Apple',
  'kind': 'apple',
  'slug': 'apple',
  'board': 'https://jobs.apple.com/en-us/search?search=security',
  'group': 'Big Tech'},
 {'name': 'Block', 'kind': 'greenhouse', 'slug': 'block', 'group': 'Big Tech'},
 {'name': 'Cisco',
  'kind': 'cisco',
  'slug': 'cisco',
  'board': 'https://careers.cisco.com/global/en',
  'categories': ['/global/en/c/product-and-engineering-jobs',
                 '/global/en/c/business-development-and-strategy-jobs',
                 '/global/en/c/other-jobs'],
  'group': 'Big Tech'},
 {'name': 'Discord', 'kind': 'greenhouse', 'slug': 'discord', 'group': 'Big Tech'},
 {'name': 'Dropbox', 'kind': 'greenhouse', 'slug': 'dropbox', 'group': 'Big Tech'},
 {'name': 'GitHub',
  'kind': 'github',
  'slug': 'github',
  'board': 'https://www.github.careers/careers-home/jobs?keywords=security',
  'search_url': 'https://www.github.careers/careers-home/jobs?keywords=security',
  'group': 'Big Tech'},
 {'name': 'Google',
  'kind': 'google',
  'slug': 'google',
  'board': 'https://www.google.com/about/careers/applications/jobs/results/?q=security&hl=en_US',
  'search_url': 'https://www.google.com/about/careers/applications/jobs/results?hl=en_US&target_level=DIRECTOR_PLUS&target_level=ADVANCED&employment_type=FULL_TIME',
  'group': 'Big Tech'},
 {'name': 'IBM',
  'kind': 'ibm',
  'slug': 'ibm',
  'board': 'https://www.ibm.com/careers/search?q=security',
  'search_url': 'https://www.ibm.com/careers/search?q=security',
  'group': 'Big Tech'},
 {'name': 'Intel',
  'kind': 'workday',
  'slug': 'intel',
  'board': 'https://intel.wd1.myworkdayjobs.com/External',
  'group': 'Big Tech'},
 {'name': 'LinkedIn',
  'kind': 'linkedin',
  'slug': 'linkedin',
  'board': 'https://www.linkedin.com/jobs/search/?f_C=1337&geoId=103644278',
  'urls': ['https://www.linkedin.com/jobs/search/?f_C=1337&geoId=103644278&f_TPR=r604800&f_SAL=f_SA_id_227001%3A278001%2C272003%2C279001%24f_SA_id_226001%3A272015&keywords=jobs',
           'https://www.linkedin.com/jobs/search/?f_C=1337&geoId=103644278&f_TPR=r2592000&f_SAL=f_SA_id_227001%3A278001%2C272003%2C279001%24f_SA_id_226001%3A272015&keywords=jobs',
           'https://www.linkedin.com/jobs/search/?f_C=1337&geoId=103644278'],
  'group': 'Big Tech'},
 {'name': 'Meta',
  'kind': 'meta',
  'slug': 'meta',
  'board': 'https://www.metacareers.com/jobsearch/?q=security',
  'group': 'Big Tech'},
 {'name': 'Microsoft',
  'kind': 'microsoft',
  'slug': 'microsoft',
  'board': 'https://apply.careers.microsoft.com/careers?query=Security&pid=1970393556942260&sort_by=relevance',
  'group': 'Big Tech'},
 {'name': 'Netflix',
  'kind': 'eightfold',
  'slug': 'netflix',
  'host': 'https://explore.jobs.netflix.net',
  'domain': 'netflix.com',
  'group': 'Big Tech'},
 {'name': 'NVIDIA',
  'kind': 'phenom',
  'slug': 'nvidia',
  'board': 'https://jobs.nvidia.com/careers?query=Security&pid=893394830937&sort_by=relevance',
  'search_url': 'https://jobs.nvidia.com/careers?query=Security&sort_by=relevance',
  'group': 'Big Tech'},
 {'name': 'Palantir', 'kind': 'lever', 'slug': 'palantir', 'group': 'Big Tech'},
 {'name': 'PayPal',
  'kind': 'workday',
  'slug': 'paypal',
  'board': 'https://paypal.wd1.myworkdayjobs.com/jobs',
  'group': 'Big Tech'},
 {'name': 'Pinterest', 'kind': 'greenhouse', 'slug': 'pinterest', 'group': 'Big Tech'},
 {'name': 'Proton', 'kind': 'greenhouse', 'slug': 'proton', 'board': 'https://proton.me/careers', 'group': 'Big Tech'},
 {'name': 'Qualcomm',
  'kind': 'phenom',
  'slug': 'qualcomm',
  'board': 'https://careers.qualcomm.com/careers',
  'search_url': 'https://careers.qualcomm.com/careers?query=security&sort_by=relevance',
  'group': 'Big Tech'},
 {'name': 'Robinhood', 'kind': 'greenhouse', 'slug': 'robinhood', 'group': 'Big Tech'},
 {'name': 'Roblox', 'kind': 'greenhouse', 'slug': 'roblox', 'group': 'Big Tech'},
 {'name': 'Salesforce',
  'kind': 'workday',
  'slug': 'salesforce',
  'board': 'https://salesforce.wd12.myworkdayjobs.com/External_Career_Site',
  'group': 'Big Tech'},
 {'name': 'SAP',
  'kind': 'pw',
  'slug': 'sap',
  'board': 'https://jobs.sap.com/search/?q=&locationsearch=&searchResultView=LIST',
  'search_url': 'https://jobs.sap.com/search/?q=&locationsearch=&searchResultView=LIST',
  'link_re': 'href="(/en/jobs/\\d+/[^"#?]+)"',
  'origin': 'https://jobs.sap.com',
  'group': 'Big Tech'},
 {'name': 'Stripe', 'kind': 'greenhouse', 'slug': 'stripe', 'group': 'Big Tech'},
 {'name': 'Twilio', 'kind': 'greenhouse', 'slug': 'twilio', 'group': 'Big Tech'},
 {'name': 'Unity',
  'kind': 'workday',
  'slug': 'unity',
  'board': 'https://unitytech.wd1.myworkdayjobs.com/Unity',
  'group': 'Big Tech'},
 {'name': 'VMware (Broadcom)',
  'kind': 'workday',
  'slug': 'broadcom',
  'board': 'https://broadcom.wd1.myworkdayjobs.com/External_Career',
  'group': 'Big Tech'},
 {'name': 'Anthropic', 'kind': 'greenhouse', 'slug': 'anthropic', 'group': 'Major AI Companies'},
 {'name': 'Cohere', 'kind': 'ashby', 'slug': 'cohere', 'group': 'Major AI Companies'},
 {'name': 'Cursor',
  'kind': 'ashby',
  'slug': 'cursor',
  'board': 'https://cursor.com/careers',
  'group': 'Major AI Companies'},
 {'name': 'DeepL', 'kind': 'ashby', 'slug': 'DeepL', 'group': 'Major AI Companies'},
 {'name': 'Eleven Labs', 'kind': 'ashby', 'slug': 'elevenlabs', 'group': 'Major AI Companies'},
 {'name': 'HF',
  'kind': 'workable',
  'slug': 'huggingface',
  'board': 'https://apply.workable.com/huggingface/',
  'group': 'Major AI Companies'},
 {'name': 'Mistral', 'kind': 'ashby', 'slug': 'mistral.ai', 'group': 'Major AI Companies'},
 {'name': 'OpenAI', 'kind': 'ashby', 'slug': 'openai', 'group': 'Major AI Companies'},
 {'name': 'Scale AI',
  'kind': 'scale',
  'slug': 'scale',
  'board': 'https://scale.com/careers',
  'search_url': 'https://scale.com/careers',
  'group': 'Major AI Companies'},
 {'name': 'Sony AI',
  'kind': 'pw',
  'slug': 'sonyai',
  'board': 'https://ai.sony/join-us',
  'search_url': 'https://ai.sony/join-us',
  'link_re': 'href="(https?://[^"]*(?:jobs|careers|job-postings|apply)[^"]*|/(?:jobs|careers|open-roles)/[^"#?]+)"',
  'origin': 'https://ai.sony',
  'group': 'Major AI Companies'},
 {'name': 'Ableton',
  'kind': 'ableton',
  'slug': 'ableton',
  'board': 'https://www.ableton.com/en/jobs/',
  'group': 'Music Companies'},
 {'name': 'Arturia',
  'kind': 'lucca',
  'slug': 'arturia-france',
  'board': 'https://jobs.world.luccasoftware.com/arturia-france',
  'group': 'Music Companies'},
 {'name': 'Avid',
  'kind': 'workday',
  'slug': 'avid',
  'board': 'https://avid.wd5.myworkdayjobs.com/AVID',
  'group': 'Music Companies'},
 {'name': 'Boris FX / iZotope',
  'kind': 'pw',
  'slug': 'borisfx',
  'board': 'https://borisfx.com/company/careers/',
  'search_url': 'https://borisfx.com/company/careers/',
  'link_re': 'href="(/company/careers/#[a-z0-9-]+)"',
  'origin': 'https://borisfx.com',
  'group': 'Music Companies'},
 {'name': 'Bose',
  'kind': 'bose',
  'slug': 'bose',
  'board': 'https://careers.bose.com/us/en',
  'search_url': 'https://careers.bose.com/us/en?query=&sort_by=relevance',
  'group': 'Music Companies'},
 {'name': 'Boss',
  'kind': 'boss',
  'slug': 'boss',
  'board': 'https://www.boss.info/uk/company/employment_opportunities/employment_opportunities/',
  'group': 'Music Companies'},
 {'name': 'Dolby',
  'kind': 'phenom',
  'slug': 'dolby',
  'board': 'https://jobs.dolby.com/careers',
  'search_url': 'https://jobs.dolby.com/careers?query=&sort_by=relevance',
  'group': 'Music Companies'},
 {'name': 'Elektron',
  'kind': 'teamtailor',
  'slug': 'elektron',
  'board': 'https://careers.elektron.se/jobs',
  'group': 'Music Companies'},
 {'name': 'Fender', 'kind': 'greenhouse', 'slug': 'fender', 'group': 'Music Companies'},
 {'name': 'inMusic Brands',
  'kind': 'pinpoint',
  'slug': 'inmusicbrands',
  'display_name': 'inMusic Brands (including Native Instruments)',
  'board': 'https://inmusicbrands.pinpointhq.com/',
  'group': 'Music Companies'},
 {'name': 'Marshall',
  'kind': 'teamtailor',
  'slug': 'marshall',
  'board': 'https://careers.marshall.com/jobs',
  'group': 'Music Companies'},
 {'name': 'MOTU',
  'kind': 'pw',
  'slug': 'motu',
  'board': 'https://motu.com/en-us/company/careers/',
  'search_url': 'https://motu.com/en-us/company/careers/',
  'link_re': 'href="(/en-us/company/careers/(?!$)[a-z0-9-]+/?)"',
  'origin': 'https://motu.com',
  'group': 'Music Companies'},
 {'name': 'Neural DSP',
  'kind': 'pw',
  'slug': 'neuraldsp',
  'board': 'https://careers.neuraldsp.com/',
  'search_url': 'https://revolutpeople.com/neural-dsp/public/careers/',
  'link_re': 'href="(/neural-dsp/public/careers/[^"#?]+|https?://revolutpeople\\.com/neural-dsp/public/careers/[^"#?]+)"',
  'origin': 'https://revolutpeople.com',
  'group': 'Music Companies'},
 {'name': 'Output', 'kind': 'ashby', 'slug': 'output', 'group': 'Music Companies'},
 {'name': 'Pioneer DJ', 'kind': 'ashby', 'slug': 'pioneer', 'group': 'Music Companies'},
 {'name': 'Roland',
  'kind': 'teamtailor',
  'slug': 'roland',
  'board': 'https://www.rolandcareers.com/jobs',
  'group': 'Music Companies'},
 {'name': 'Sennheiser',
  'kind': 'successfactors',
  'slug': 'sennheiser',
  'board': 'https://jobs.sennheiser.com/search/?q=&locationsearch=&locale=en_US&searchResultView=LIST',
  'group': 'Music Companies'},
 {'name': 'Seymour Duncan',
  'kind': 'pw',
  'slug': 'seymour',
  'board': 'https://www.seymourduncan.com/company/join-our-team',
  'search_url': 'https://www.seymourduncan.com/company/join-our-team',
  'link_re': 'href="(https?://yoursmartsource\\.hiringthing\\.com/job/\\d+/[a-z0-9-]+|https?://(?:www\\.)?seymourduncan\\.com/[a-z0-9-]+-job-posting|/[a-z0-9-]+-job-posting)"',
  'origin': 'https://www.seymourduncan.com',
  'group': 'Music Companies'},
 {'name': 'Slate Digital', 'kind': 'ashby', 'slug': 'slate', 'group': 'Music Companies'},
 {'name': 'Softube',
  'kind': 'bamboohr',
  'slug': 'softube',
  'board': 'https://softube.bamboohr.com/careers',
  'group': 'Music Companies'},
 {'name': 'Sonos',
  'kind': 'workday',
  'slug': 'sonos',
  'board': 'https://sonos.wd1.myworkdayjobs.com/Sonos',
  'group': 'Music Companies'},
 {'name': 'Spitfire Audio', 'kind': 'greenhouse', 'slug': 'spitfire', 'group': 'Music Companies'},
 {'name': 'Splice', 'kind': 'greenhouse', 'slug': 'splice', 'group': 'Music Companies'},
 {'name': 'Steinberg',
  'kind': 'pw',
  'slug': 'steinberg',
  'board': 'https://www.steinberg.net/careers/vacancies/',
  'search_url': 'https://www.steinberg.net/careers/vacancies/',
  'link_re': 'href="(https?://www\\.steinberg\\.net/careers/[^"#?]+|/careers/[^"#?/]+/[^"#?]+)"',
  'origin': 'https://www.steinberg.net',
  'group': 'Music Companies'},
 {'name': 'Suno', 'kind': 'ashby', 'slug': 'suno', 'group': 'Music Companies'},
 {'name': 'Udio', 'kind': 'greenhouse', 'slug': 'udio', 'group': 'Music Companies'},
 {'name': 'Universal Audio', 'kind': 'greenhouse', 'slug': 'universalaudio', 'group': 'Music Companies'},
 {'name': 'Yamaha',
  'kind': 'umantis',
  'slug': 'yamaha',
  'board': 'https://recruitingapp-5230.de.umantis.com/Jobs/All',
  'search_url': 'https://recruitingapp-5230.de.umantis.com/Jobs/All',
  'group': 'Music Companies'},
 {'name': 'Alan', 'kind': 'ashby', 'slug': 'alan', 'group': 'Other'},
 {'name': 'Brex', 'kind': 'greenhouse', 'slug': 'brex', 'group': 'Other'},
 {'name': 'Databricks', 'kind': 'greenhouse', 'slug': 'databricks', 'group': 'Other'},
 {'name': 'Datadog', 'kind': 'greenhouse', 'slug': 'datadog', 'group': 'Other'},
 {'name': 'Dataiku', 'kind': 'greenhouse', 'slug': 'dataiku', 'group': 'Other'},
 {'name': 'Doctolib', 'kind': 'ashby', 'slug': 'doctolib', 'group': 'Other'},
 {'name': 'Fastly', 'kind': 'greenhouse', 'slug': 'fastly', 'group': 'Other'},
 {'name': 'Figma', 'kind': 'greenhouse', 'slug': 'figma', 'group': 'Other'},
 {'name': 'Fivetran', 'kind': 'greenhouse', 'slug': 'fivetran', 'group': 'Other'},
 {'name': 'GitLab', 'kind': 'greenhouse', 'slug': 'gitlab', 'group': 'Other'},
 {'name': 'Grafana Labs', 'kind': 'greenhouse', 'slug': 'grafanalabs', 'group': 'Other'},
 {'name': 'HashiCorp', 'kind': 'workable', 'slug': 'hashicorp', 'group': 'Other'},
 {'name': 'Hex', 'kind': 'ashby', 'slug': 'hex', 'group': 'Other'},
 {'name': 'Linear', 'kind': 'ashby', 'slug': 'linear', 'group': 'Other'},
 {'name': 'Mercury', 'kind': 'ashby', 'slug': 'mercury', 'group': 'Other'},
 {'name': 'MongoDB', 'kind': 'greenhouse', 'slug': 'mongodb', 'group': 'Other'},
 {'name': 'Owkin', 'kind': 'ashby', 'slug': 'owkin', 'group': 'Other'},
 {'name': 'Qonto', 'kind': 'ashby', 'slug': 'qonto', 'group': 'Other'},
 {'name': 'Reddit', 'kind': 'greenhouse', 'slug': 'reddit', 'group': 'Other'},
 {'name': 'Snowflake', 'kind': 'ashby', 'slug': 'snowflake', 'group': 'Other'},
 {'name': 'Vercel', 'kind': 'greenhouse', 'slug': 'vercel', 'group': 'Other'},
 {'name': '1Password', 'kind': 'ashby', 'slug': '1password', 'group': 'Security Companies'},
 {'name': 'Aisle',
  'kind': 'ashby',
  'slug': 'aisle',
  'board': 'https://aisle.com/careers',
  'group': 'Security Companies'},
 {'name': 'BeyondTrust', 'kind': 'greenhouse', 'slug': 'beyondtrust', 'group': 'Security Companies'},
 {'name': 'Bitwarden', 'kind': 'greenhouse', 'slug': 'bitwarden', 'group': 'Security Companies'},
 {'name': 'Cape Privacy', 'kind': 'ashby', 'slug': 'cape', 'group': 'Security Companies'},
 {'name': 'Chainguard', 'kind': 'greenhouse', 'slug': 'chainguard', 'group': 'Security Companies'},
 {'name': 'Checkmarx',
  'kind': 'checkmarx',
  'slug': 'checkmarx',
  'board': 'https://checkmarx.com/company/careers/',
  'search_url': 'https://checkmarx.com/company/careers/',
  'group': 'Security Companies'},
 {'name': 'Cloudflare', 'kind': 'greenhouse', 'slug': 'cloudflare', 'group': 'Security Companies'},
 {'name': 'Corgea',
  'kind': 'pw',
  'slug': 'corgea',
  'board': 'https://www.ycombinator.com/companies/corgea/jobs',
  'search_url': 'https://www.ycombinator.com/companies/corgea/jobs',
  'link_re': 'href="(/companies/corgea/jobs/[^"#?]+)"',
  'origin': 'https://www.ycombinator.com',
  'group': 'Security Companies'},
 {'name': 'CrowdStrike',
  'kind': 'pw',
  'slug': 'crowdstrike',
  'board': 'https://crowdstrike.wd5.myworkdayjobs.com/en-US/crowdstrikecareers?q=security',
  'search_url': 'https://crowdstrike.wd5.myworkdayjobs.com/en-US/crowdstrikecareers?q=security',
  'link_re': 'href="(/en-US/crowdstrikecareers/job/[^"]+)"',
  'origin': 'https://crowdstrike.wd5.myworkdayjobs.com',
  'wait_selector': "a[href*='/crowdstrikecareers/job/']",
  'group': 'Security Companies'},
 {'name': 'Cybereason', 'kind': 'greenhouse', 'slug': 'cybereason', 'group': 'Security Companies'},
 {'name': 'DepthFirst', 'kind': 'ashby', 'slug': 'depthfirst', 'group': 'Security Companies'},
 {'name': 'Doppler', 'kind': 'ashby', 'slug': 'doppler', 'group': 'Security Companies'},
 {'name': 'Drata', 'kind': 'ashby', 'slug': 'drata', 'group': 'Security Companies'},
 {'name': 'Elastic', 'kind': 'greenhouse', 'slug': 'elastic', 'group': 'Security Companies'},
 {'name': 'Endor Labs', 'kind': 'greenhouse', 'slug': 'endorlabs', 'group': 'Security Companies'},
 {'name': 'GitGuardian',
  'kind': 'pw',
  'slug': 'gitguardian',
  'board': 'https://www.gitguardian.com/careers',
  'search_url': 'https://www.gitguardian.com/careers',
  'link_re': 'href="(/job-openings/\\d+-[a-z0-9-]+)"',
  'origin': 'https://www.gitguardian.com',
  'group': 'Security Companies'},
 {'name': 'Netskope', 'kind': 'greenhouse', 'slug': 'netskope', 'group': 'Security Companies'},
 {'name': 'Nord Security', 'kind': 'ashby', 'slug': 'nord-security', 'group': 'Security Companies'},
 {'name': 'Okta', 'kind': 'greenhouse', 'slug': 'okta', 'group': 'Security Companies'},
 {'name': 'Pixee',
  'kind': 'pixee',
  'slug': 'pixee',
  'board': 'https://app.dover.com/jobs/pixee',
  'search_url': 'https://app.dover.com/jobs/pixee',
  'group': 'Security Companies'},
 {'name': 'PQShield', 'kind': 'greenhouse', 'slug': 'pqshield', 'group': 'Security Companies'},
 {'name': 'SandboxAQ', 'kind': 'ashby', 'slug': 'sandboxaq', 'group': 'Security Companies'},
 {'name': 'Semgrep',
  'kind': 'pw',
  'slug': 'semgrep',
  'board': 'https://semgrep.dev/about/careers/',
  'search_url': 'https://semgrep.dev/about/careers/',
  'link_re': 'href="(https?://[^"]*greenhouse[^"]*/semgrep/jobs/\\d+[^"]*|/about/careers/[^"#?/]+/?)"',
  'origin': 'https://semgrep.dev',
  'wait_selector': "a[href*='/jobs/'], a[href*='/careers/']",
  'group': 'Security Companies'},
 {'name': 'Snyk', 'kind': 'ashby', 'slug': 'snyk', 'group': 'Security Companies'},
 {'name': 'Socket', 'kind': 'ashby', 'slug': 'socket', 'group': 'Security Companies'},
 {'name': 'Tailscale', 'kind': 'greenhouse', 'slug': 'tailscale', 'group': 'Security Companies'},
 {'name': 'Wiz', 'kind': 'ashby', 'slug': 'wiz', 'group': 'Security Companies'},
 {'name': 'XBOW', 'kind': 'ashby', 'slug': 'xbowcareers', 'group': 'Security Companies'},
 {'name': 'Yubico', 'kind': 'greenhouse', 'slug': 'yubico', 'group': 'Security Companies'},
 {'name': 'ZeroPath',
  'kind': 'pw',
  'slug': 'zeropath',
  'board': 'https://zeropath.com/careers',
  'search_url': 'https://zeropath.com/careers',
  'link_re': 'href="(https?://jobs\\.ashbyhq\\.com/[^"#?]+/[a-f0-9-]{20,}|/careers/[^"#?]+|https?://[^"]*(?:greenhouse|lever|workable|ashby)[^"]*)"',
  'origin': 'https://zeropath.com',
  'group': 'Security Companies'},

 # --- Verified 2026-10-07 via debug/probe_new_catalog.py --------------------
 # Cars
 {'name': 'Lucid Motors', 'kind': 'greenhouse', 'slug': 'lucidmotors', 'group': 'Cars'},
 {'name': 'Scout Motors', 'kind': 'greenhouse', 'slug': 'scoutmotors', 'group': 'Cars'},
 # Verified 2026-10-07 via debug/probe_misses_pw.py — Lever/pw recovered
 # after JS render.
 {'name': 'Zoox', 'kind': 'lever', 'slug': 'zoox', 'group': 'Cars'},
 # Verified 2026-10-07 via debug/probe_rescue.py (round 3).
 {'name': 'Toyota',
  'kind': 'workday',
  'slug': 'toyota',
  'board': 'https://toyota.wd503.myworkdayjobs.com/TMNA',
  'group': 'Cars'},
 {'name': 'Polestar',
  'kind': 'workday',
  'slug': 'polestar',
  'board': 'https://polestarcars.wd1.myworkdayjobs.com/External',
  'group': 'Cars'},
 {'name': 'BMW',
  'kind': 'pw',
  'slug': 'bmw',
  'board': 'https://www.bmwgroup.jobs/en.html',
  'search_url': 'https://www.bmwgroup.jobs/en.html',
  'link_re': 'href="(/en/jobfinder/job-description-copy\\.\\d+\\.html)"',
  'origin': 'https://www.bmwgroup.jobs',
  'wait_selector': "a[href*='/jobfinder/']",
  'scroll': True,
  'group': 'Cars'},
 {'name': 'GM',
  'kind': 'pw',
  'slug': 'gm',
  'board': 'https://search-careers.gm.com/en/',
  'search_url': 'https://search-careers.gm.com/en/',
  'link_re': 'href="(/en/jobs/jr-\\d+/[a-z0-9-]+/)"',
  'origin': 'https://search-careers.gm.com',
  'wait_selector': "a[href*='/jobs/jr-']",
  'scroll': True,
  'group': 'Cars'},

 # Media
 {'name': 'The New York Times', 'kind': 'greenhouse', 'slug': 'thenewyorktimes', 'group': 'Media'},
 # Verified 2026-10-07 via debug/probe_misses_pw.py (JS-render pass).
 {'name': 'Substack', 'kind': 'ashby', 'slug': 'substack', 'group': 'Media'},
 # Verified 2026-10-07 via debug/probe_rescue.py.
 {'name': 'Dow Jones',
  'kind': 'workday',
  'slug': 'dowjones',
  'board': 'https://newscorp.wd3.myworkdayjobs.com/Dow_Jones_Careers',
  'group': 'Media'},
 {'name': 'SoundCloud', 'kind': 'greenhouse', 'slug': 'soundcloud71', 'group': 'Media'},
 {'name': 'The Atlantic',
  'kind': 'workday',
  'slug': 'theatlantic',
  'board': 'https://atlanticmedia.wd1.myworkdayjobs.com/Careers',
  'group': 'Media'},
 {'name': 'Vox Media', 'kind': 'greenhouse', 'slug': 'voxmedia', 'group': 'Media'},
 {'name': 'Axios', 'kind': 'greenhouse', 'slug': 'axios', 'group': 'Media'},
 {'name': 'Peloton', 'kind': 'greenhouse', 'slug': 'peloton', 'group': 'Media'},
 {'name': 'Semafor', 'kind': 'greenhouse', 'slug': 'semafor', 'group': 'Media'},

 # Startups (YC-recent / unicorns / dev-tools not already in another bucket)
 {'name': 'Decagon', 'kind': 'ashby', 'slug': 'decagon', 'group': 'Startups'},
 {'name': 'Supabase', 'kind': 'ashby', 'slug': 'supabase', 'group': 'Startups'},
 {'name': 'PostHog', 'kind': 'ashby', 'slug': 'posthog', 'group': 'Startups'},
 {'name': 'Resend', 'kind': 'ashby', 'slug': 'resend', 'group': 'Startups'},
 {'name': 'Dust', 'kind': 'ashby', 'slug': 'dust', 'group': 'Startups'},
 {'name': 'Granola', 'kind': 'ashby', 'slug': 'granola', 'group': 'Startups'},
 {'name': 'Ramp', 'kind': 'ashby', 'slug': 'ramp', 'group': 'Startups'},
 {'name': 'Carta', 'kind': 'greenhouse', 'slug': 'carta', 'group': 'Startups'},
 {'name': 'Chime', 'kind': 'greenhouse', 'slug': 'chime', 'group': 'Startups'},
 {'name': 'Affirm', 'kind': 'greenhouse', 'slug': 'affirm', 'group': 'Startups'},
 {'name': 'Airtable', 'kind': 'greenhouse', 'slug': 'airtable', 'group': 'Startups'},
 {'name': 'PlanetScale', 'kind': 'greenhouse', 'slug': 'planetscale', 'group': 'Startups'},
 {'name': 'Neon', 'kind': 'ashby', 'slug': 'neon', 'group': 'Startups'},
 {'name': 'Render', 'kind': 'ashby', 'slug': 'render', 'group': 'Startups'},
 {'name': 'Vapi', 'kind': 'ashby', 'slug': 'vapi', 'group': 'Startups'},
 {'name': 'Buildkite', 'kind': 'greenhouse', 'slug': 'buildkite', 'group': 'Startups'},
 {'name': 'Clerk', 'kind': 'ashby', 'slug': 'clerk', 'group': 'Startups'},
 {'name': 'WorkOS', 'kind': 'ashby', 'slug': 'workos', 'group': 'Startups'},
 {'name': 'Temporal', 'kind': 'ashby', 'slug': 'temporal', 'group': 'Startups'},
 {'name': 'Mozilla', 'kind': 'greenhouse', 'slug': 'mozilla', 'group': 'Startups'},
 {'name': 'Instacart', 'kind': 'greenhouse', 'slug': 'instacart', 'group': 'Startups'},

 # Verified 2026-10-07 via debug/probe_misses.py — ashby slug extracted
 # from the vanity career page's embedded Ashby references.
 {'name': 'Notion', 'kind': 'ashby', 'slug': 'notion', 'group': 'Startups'},
 # Verified 2026-10-07 via debug/probe_misses_pw.py (JS-render pass).
 {'name': 'Zapier', 'kind': 'ashby', 'slug': 'zapier', 'group': 'Startups'},
 # Verified 2026-10-07 via debug/probe_rescue.py.
 {'name': 'Convex', 'kind': 'ashby', 'slug': 'convex-dev', 'group': 'AI Startups'},
 {'name': 'DoorDash',
  'kind': 'pw',
  'slug': 'doordash',
  'board': 'https://careersatdoordash.com/job-search/',
  'search_url': 'https://careersatdoordash.com/job-search/',
  'link_re': 'href="(https://careersatdoordash\\.com/jobs/[a-z0-9-]+/\\d+)"',
  'origin': 'https://careersatdoordash.com',
  'wait_selector': "a[href*='careersatdoordash.com/jobs/']",
  'scroll': True,
  'group': 'Startups'},

 # pw-generic entries — link_re verified against the saved debug dump.
 # Re-run debug/probe_misses_regex.py to re-check if a site changes shape.
 {'name': 'Shopify',
  'kind': 'pw',
  'slug': 'shopify',
  'board': 'https://www.shopify.com/careers',
  'search_url': 'https://www.shopify.com/careers/search',
  'link_re': 'href="(/careers/[^"#?]+_[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})"',
  'origin': 'https://www.shopify.com',
  'wait_selector': "a[href*='/careers/']",
  'scroll': True,
  'group': 'Startups'},
 {'name': 'Plaid',
  'kind': 'pw',
  'slug': 'plaid',
  'board': 'https://plaid.com/careers/openings/',
  'search_url': 'https://plaid.com/careers/openings/',
  'link_re': 'href="(/careers/openings/[^"#?]+/[^"#?]+/[^"#?]+/)"',
  'origin': 'https://plaid.com',
  'wait_selector': "a[href*='/careers/openings/']",
  'scroll': True,
  'group': 'Startups'},
 {'name': 'Retool',
  'kind': 'pw',
  'slug': 'retool',
  'board': 'https://retool.com/careers',
  'search_url': 'https://retool.com/careers',
  'link_re': 'href="(/careers/[a-z0-9-]+--[a-z0-9-]+--[a-z0-9-]+)"',
  'origin': 'https://retool.com',
  'wait_selector': "a[href*='/careers/']",
  'scroll': True,
  'group': 'Startups'},
 {'name': 'Fly.io',
  'kind': 'pw',
  'slug': 'flyio',
  'board': 'https://fly.io/jobs/',
  'search_url': 'https://fly.io/jobs/',
  'link_re': 'href="(/jobs/[a-z][a-z0-9-]+/)"',
  'origin': 'https://fly.io',
  'wait_selector': "a[href*='/jobs/']",
  'group': 'Startups'},

 # FHE
 # Zama is scraped via the WTJ API (api.welcometothejungle.com/api/v3)
 # — more reliable than the old Playwright scrape of jobs.zama.org.
 # The `kind` stays `wttj_company` (that's the fetcher), but the group
 # is 'FHE' so Zama sits next to Fhenix / Duality in the onboarding
 # catalog, not buried under the generic WTJ bucket.
 {'name': 'Zama', 'kind': 'wttj_company', 'slug': 'zama',
  'board': 'https://www.welcometothejungle.com/fr/companies/zama',
  'group': 'FHE'},
 # Well-known French tech companies on WTJ. Seeded 2026-10-07 — slugs
 # are the ones used in https://www.welcometothejungle.com/fr/companies/<slug>.
 # Some may 404 (WTJ moved them / renamed them); those return 0 jobs
 # and should be removed from this list when spotted.
 # Slug currently returns 0 jobs — real slug TBD via
 # debug/probe_wttj_slug_find.py "Aircall". Entry kept per CLAUDE.md
 # ("Never remove what doesn't work — FIX it").
 {'name': 'Aircall', 'kind': 'wttj_company', 'slug': 'aircall',
  'board': 'https://www.welcometothejungle.com/fr/companies/aircall',
  'group': 'Welcome to the Jungle'},
 {'name': 'Back Market', 'kind': 'wttj_company', 'slug': 'back-market',
  'board': 'https://www.welcometothejungle.com/fr/companies/back-market',
  'group': 'Welcome to the Jungle'},
 {'name': 'BlaBlaCar', 'kind': 'wttj_company', 'slug': 'blablacar',
  'board': 'https://www.welcometothejungle.com/fr/companies/blablacar',
  'group': 'Welcome to the Jungle'},
 {'name': 'Deezer', 'kind': 'wttj_company', 'slug': 'deezer',
  'board': 'https://www.welcometothejungle.com/fr/companies/deezer',
  'group': 'Welcome to the Jungle'},
 {'name': 'Spendesk', 'kind': 'wttj_company', 'slug': 'spendesk',
  'board': 'https://www.welcometothejungle.com/fr/companies/spendesk',
  'group': 'Welcome to the Jungle'},
 {'name': 'PayFit', 'kind': 'wttj_company', 'slug': 'payfit',
  'board': 'https://www.welcometothejungle.com/fr/companies/payfit',
  'group': 'Welcome to the Jungle'},
 {'name': 'Swile', 'kind': 'wttj_company', 'slug': 'swile',
  'board': 'https://www.welcometothejungle.com/fr/companies/swile',
  'group': 'Welcome to the Jungle'},
 {'name': 'Malt', 'kind': 'wttj_company', 'slug': 'malt',
  'board': 'https://www.welcometothejungle.com/fr/companies/malt',
  'group': 'Welcome to the Jungle'},
 {'name': 'Mirakl', 'kind': 'wttj_company', 'slug': 'mirakl',
  'board': 'https://www.welcometothejungle.com/fr/companies/mirakl',
  'group': 'Welcome to the Jungle'},
 # Slugs below currently 0-job — real slugs TBD (probe_wttj_slug_find.py).
 {'name': 'Contentsquare', 'kind': 'wttj_company', 'slug': 'contentsquare',
  'board': 'https://www.welcometothejungle.com/fr/companies/contentsquare',
  'group': 'Welcome to the Jungle'},
 {'name': 'Getaround', 'kind': 'wttj_company', 'slug': 'getaround',
  'board': 'https://www.welcometothejungle.com/fr/companies/getaround',
  'group': 'Welcome to the Jungle'},
 {'name': 'Pigment', 'kind': 'wttj_company', 'slug': 'pigment',
  'board': 'https://www.welcometothejungle.com/fr/companies/pigment',
  'group': 'Welcome to the Jungle'},
 {'name': '360Learning', 'kind': 'wttj_company', 'slug': '360learning',
  'board': 'https://www.welcometothejungle.com/fr/companies/360learning',
  'group': 'Welcome to the Jungle'},
 # Slugs below currently 0-job — real slugs TBD (probe_wttj_slug_find.py).
 {'name': 'OpenClassrooms', 'kind': 'wttj_company', 'slug': 'openclassrooms',
  'board': 'https://www.welcometothejungle.com/fr/companies/openclassrooms',
  'group': 'Welcome to the Jungle'},
 {'name': 'Vestiaire Collective', 'kind': 'wttj_company', 'slug': 'vestiaire-collective',
  'board': 'https://www.welcometothejungle.com/fr/companies/vestiaire-collective',
  'group': 'Welcome to the Jungle'},
 {'name': 'Shift Technology', 'kind': 'wttj_company', 'slug': 'shift-technology',
  'board': 'https://www.welcometothejungle.com/fr/companies/shift-technology',
  'group': 'Welcome to the Jungle'},
 {'name': 'Withings', 'kind': 'wttj_company', 'slug': 'withings',
  'board': 'https://www.welcometothejungle.com/fr/companies/withings',
  'group': 'Welcome to the Jungle'},
 {'name': 'Yousign', 'kind': 'wttj_company', 'slug': 'yousign',
  'board': 'https://www.welcometothejungle.com/fr/companies/yousign',
  'group': 'Welcome to the Jungle'},
 {'name': 'Lifen', 'kind': 'wttj_company', 'slug': 'lifen',
  'board': 'https://www.welcometothejungle.com/fr/companies/lifen',
  'group': 'Welcome to the Jungle'},
 # Slug currently 0-job — real slug TBD (probe_wttj_slug_find.py).
 {'name': 'Lydia', 'kind': 'wttj_company', 'slug': 'lydia-solutions',
  'board': 'https://www.welcometothejungle.com/fr/companies/lydia-solutions',
  'group': 'Welcome to the Jungle'},
 {'name': 'Fhenix',
  'kind': 'pw',
  'slug': 'fhenix',
  'board': 'https://www.fhenix.io/careers',
  'search_url': 'https://www.fhenix.io/careers',
  'link_re': 'href="(/jobs/[a-z][^"#?]*)"',
  'origin': 'https://www.fhenix.io',
  'wait_selector': "a[href*='/jobs/']",
  'group': 'FHE'},
 {'name': 'Duality',
  'kind': 'pw',
  'slug': 'duality',
  'board': 'https://dualitytech.com/careers/',
  'search_url': 'https://dualitytech.com/careers/',
  'link_re': 'href="(https?://dualitytech\\.com/careers/[a-z0-9-]+/)"',
  'origin': 'https://dualitytech.com',
  'wait_selector': "a[href*='/careers/']",
  'group': 'FHE'},

 # Blockchain / crypto
 {'name': 'Coinbase', 'kind': 'greenhouse', 'slug': 'coinbase', 'group': 'Blockchain'},
 {'name': 'Fireblocks', 'kind': 'greenhouse', 'slug': 'fireblocks', 'group': 'Blockchain'},
 {'name': 'OpenZeppelin', 'kind': 'greenhouse', 'slug': 'openzeppelin', 'group': 'Blockchain'},
 {'name': 'Phantom', 'kind': 'ashby', 'slug': 'phantom', 'group': 'Blockchain'},
 {'name': 'Aptos Labs', 'kind': 'greenhouse', 'slug': 'aptoslabs', 'group': 'Blockchain'},
 {'name': 'Consensys', 'kind': 'greenhouse', 'slug': 'consensys', 'group': 'Blockchain'},
 {'name': 'Dune', 'kind': 'ashby', 'slug': 'dune', 'group': 'Blockchain'},
 {'name': 'Paradigm', 'kind': 'ashby', 'slug': 'paradigm', 'group': 'Blockchain'},
 {'name': 'Blockchain.com', 'kind': 'greenhouse', 'slug': 'blockchain', 'group': 'Blockchain'},

 # Verified 2026-10-07 via debug/probe_misses.py — Ashby/Lever slugs
 # recovered from the companies' custom career-page HTML.
 {'name': 'Kraken', 'kind': 'ashby', 'slug': 'kraken', 'group': 'Blockchain'},
 # Verified 2026-10-07 via debug/probe_misses_pw.py (JS-render pass).
 {'name': 'Ledger', 'kind': 'ashby', 'slug': 'ledger', 'group': 'Blockchain'},
 {'name': 'Alchemy', 'kind': 'ashby', 'slug': 'alchemy', 'group': 'Blockchain'},
 {'name': 'Mysten Labs', 'kind': 'ashby', 'slug': 'mystenlabs', 'group': 'Blockchain'},
 {'name': 'Uniswap Labs', 'kind': 'ashby', 'slug': 'uniswap', 'group': 'Blockchain'},
 {'name': 'Immutable', 'kind': 'lever', 'slug': 'immutable', 'group': 'Blockchain'},
 # Verified 2026-10-07 via debug/probe_rescue.py.
 {'name': 'Chainalysis', 'kind': 'ashby', 'slug': 'chainalysis-careers', 'group': 'Blockchain'},
 {'name': 'Circle',
  'kind': 'workday',
  'slug': 'circle',
  'board': 'https://circle.wd1.myworkdayjobs.com/Circle',
  'group': 'Blockchain'}]
