"""catalog.py — the full set of companies this engine can scrape.

This is the "menu" the onboarding wizard shows. Each entry carries just
enough plumbing (kind + slug + any ATS-specific extras like `board`,
`search_url`, `link_re`, `wait_selector`, `host`, `domain`, `urls`,
`origin`, `display_name`, `categories`) for the wizard to generate a
valid SOURCES entry in data/user_config.py.

User-tunable fields (`queries`) are intentionally NOT here — those are
personal and belong in data/user_config.py only.

Generated from data/user_config.py; see tooling/build_catalog.py if we
ever want a repeatable rebuild. For now, hand-maintained + re-run the
extraction when adding a new company.
"""

CATALOG = [{'name': 'AMI', 'kind': 'ashby', 'slug': 'ami', 'group': 'AI Startups'},
 {'name': 'Anyscale', 'kind': 'ashby', 'slug': 'anyscale', 'group': 'AI Startups'},
 {'name': 'AssemblyAI', 'kind': 'greenhouse', 'slug': 'assemblyai', 'group': 'AI Startups'},
 {'name': 'Baseten', 'kind': 'ashby', 'slug': 'baseten', 'group': 'AI Startups'},
 {'name': 'Black Forest Labs',
  'kind': 'pw',
  'slug': 'blackforestlabs',
  'board': 'https://bfl.ai/careers',
  'search_url': 'https://bfl.ai/careers',
  'link_re': 'href="(https?://[^"]*greenhouse[^"]*/blackforestlabs[^"]*|/careers/[^"#?/]+/?)"',
  'origin': 'https://bfl.ai',
  'wait_selector': "a[href*='greenhouse'], a[href*='/careers/']",
  'group': 'AI Startups'},
 {'name': 'Braintrust', 'kind': 'ashby', 'slug': 'braintrust', 'group': 'AI Startups'},
 {'name': 'Cerebras', 'kind': 'ashby', 'slug': 'cerebras', 'group': 'AI Startups'},
 {'name': 'Character AI', 'kind': 'ashby', 'slug': 'character', 'group': 'AI Startups'},
 {'name': 'Cline', 'kind': 'greenhouse', 'slug': 'cline', 'group': 'AI Startups'},
 {'name': 'Cognition',
  'kind': 'ashby',
  'slug': 'cognition',
  'board': 'https://cognition.com/careers',
  'group': 'AI Startups'},
 {'name': 'Coreweave', 'kind': 'greenhouse', 'slug': 'coreweave', 'group': 'AI Startups'},
 {'name': 'Covariant', 'kind': 'greenhouse', 'slug': 'covariant', 'group': 'AI Startups'},
 {'name': 'Crusoe', 'kind': 'ashby', 'slug': 'crusoe', 'group': 'AI Startups'},
 {'name': 'Deepgram', 'kind': 'ashby', 'slug': 'deepgram', 'group': 'AI Startups'},
 {'name': 'Etched', 'kind': 'ashby', 'slug': 'etched', 'group': 'AI Startups'},
 {'name': 'Fireworks AI', 'kind': 'ashby', 'slug': 'fireworks', 'group': 'AI Startups'},
 {'name': 'Groq', 'kind': 'greenhouse', 'slug': 'groq', 'group': 'AI Startups'},
 {'name': 'H', 'kind': 'ashby', 'slug': 'hcompany', 'group': 'AI Startups'},
 {'name': 'Harvey', 'kind': 'greenhouse', 'slug': 'harvey', 'group': 'AI Startups'},
 {'name': 'Imbue', 'kind': 'greenhouse', 'slug': 'imbue', 'group': 'AI Startups'},
 {'name': 'Lambda', 'kind': 'ashby', 'slug': 'lambda', 'group': 'AI Startups'},
 {'name': 'LangChain', 'kind': 'ashby', 'slug': 'langchain', 'group': 'AI Startups'},
 {'name': 'LlamaIndex', 'kind': 'ashby', 'slug': 'llamaindex', 'group': 'AI Startups'},
 {'name': 'Luma AI', 'kind': 'greenhouse', 'slug': 'lumaai', 'group': 'AI Startups'},
 {'name': 'MatX', 'kind': 'ashby', 'slug': 'matx', 'group': 'AI Startups'},
 {'name': 'Modal', 'kind': 'ashby', 'slug': 'modal', 'group': 'AI Startups'},
 {'name': 'Nebius', 'kind': 'greenhouse', 'slug': 'nebius', 'group': 'AI Startups'},
 {'name': 'Nomic', 'kind': 'ashby', 'slug': 'nomic', 'group': 'AI Startups'},
 {'name': 'Perplexity', 'kind': 'ashby', 'slug': 'perplexity', 'group': 'AI Startups'},
 {'name': 'Physical Intelligence', 'kind': 'ashby', 'slug': 'physicalintelligence', 'group': 'AI Startups'},
 {'name': 'Pika', 'kind': 'ashby', 'slug': 'pika', 'group': 'AI Startups'},
 {'name': 'Pinecone', 'kind': 'ashby', 'slug': 'pinecone', 'group': 'AI Startups'},
 {'name': 'Poolside', 'kind': 'ashby', 'slug': 'poolside', 'group': 'AI Startups'},
 {'name': 'Prime Intellect', 'kind': 'ashby', 'slug': 'primeintellect', 'group': 'AI Startups'},
 {'name': 'Rain', 'kind': 'ashby', 'slug': 'rain', 'group': 'AI Startups'},
 {'name': 'Replit', 'kind': 'ashby', 'slug': 'replit', 'group': 'AI Startups'},
 {'name': 'Rewind AI', 'kind': 'ashby', 'slug': 'rewind', 'group': 'AI Startups'},
 {'name': 'Runway', 'kind': 'ashby', 'slug': 'runway', 'group': 'AI Startups'},
 {'name': 'Sakana AI', 'kind': 'workable', 'slug': 'sakana-ai', 'group': 'AI Startups'},
 {'name': 'SSI', 'kind': 'ashby', 'slug': 'ssi', 'group': 'AI Startups'},
 {'name': 'Tenstorrent', 'kind': 'greenhouse', 'slug': 'tenstorrent', 'group': 'AI Startups'},
 {'name': 'Thinking Machines', 'kind': 'ashby', 'slug': 'ThinkingMachines', 'group': 'AI Startups'},
 {'name': 'Together AI', 'kind': 'greenhouse', 'slug': 'togetherai', 'group': 'AI Startups'},
 {'name': 'Voyage AI', 'kind': 'workable', 'slug': 'voyage', 'group': 'AI Startups'},
 {'name': 'Weaviate', 'kind': 'ashby', 'slug': 'weaviate', 'group': 'AI Startups'},
 {'name': 'Writer', 'kind': 'greenhouse', 'slug': 'writer', 'group': 'AI Startups'},
 {'name': 'Zed', 'kind': 'ashby', 'slug': 'zed', 'group': 'AI Startups'},
 {'name': 'Adobe',
  'kind': 'workday',
  'slug': 'adobe',
  'board': 'https://adobe.wd5.myworkdayjobs.com/external_experienced',
  'group': 'Big Tech'},
 {'name': 'Airbnb', 'kind': 'greenhouse', 'slug': 'airbnb', 'group': 'Big Tech'},
 {'name': 'Apple',
  'kind': 'apple',
  'slug': 'apple',
  'board': 'https://jobs.apple.com/en-us/search?search=security',
  'group': 'Big Tech'},
 {'name': 'Block', 'kind': 'greenhouse', 'slug': 'block', 'group': 'Big Tech'},
 {'name': 'Cisco',
  'kind': 'cisco',
  'slug': 'cisco',
  'board': 'https://careers.cisco.com/global/en',
  'categories': ['/global/en/c/product-and-engineering-jobs',
                 '/global/en/c/business-development-and-strategy-jobs',
                 '/global/en/c/other-jobs'],
  'group': 'Big Tech'},
 {'name': 'Discord', 'kind': 'greenhouse', 'slug': 'discord', 'group': 'Big Tech'},
 {'name': 'Dropbox', 'kind': 'greenhouse', 'slug': 'dropbox', 'group': 'Big Tech'},
 {'name': 'GitHub',
  'kind': 'github',
  'slug': 'github',
  'board': 'https://www.github.careers/careers-home/jobs?keywords=security',
  'search_url': 'https://www.github.careers/careers-home/jobs?keywords=security',
  'group': 'Big Tech'},
 {'name': 'Google',
  'kind': 'google',
  'slug': 'google',
  'board': 'https://www.google.com/about/careers/applications/jobs/results/?q=security&hl=en_US',
  'search_url': 'https://www.google.com/about/careers/applications/jobs/results?hl=en_US&target_level=DIRECTOR_PLUS&target_level=ADVANCED&employment_type=FULL_TIME',
  'group': 'Big Tech'},
 {'name': 'IBM',
  'kind': 'ibm',
  'slug': 'ibm',
  'board': 'https://www.ibm.com/careers/search?q=security',
  'search_url': 'https://www.ibm.com/careers/search?q=security',
  'group': 'Big Tech'},
 {'name': 'Intel',
  'kind': 'workday',
  'slug': 'intel',
  'board': 'https://intel.wd1.myworkdayjobs.com/External',
  'group': 'Big Tech'},
 {'name': 'LinkedIn',
  'kind': 'linkedin',
  'slug': 'linkedin',
  'board': 'https://www.linkedin.com/jobs/search/?f_C=1337&geoId=103644278',
  'urls': ['https://www.linkedin.com/jobs/search/?f_C=1337&geoId=103644278&f_TPR=r604800&f_SAL=f_SA_id_227001%3A278001%2C272003%2C279001%24f_SA_id_226001%3A272015&keywords=jobs',
           'https://www.linkedin.com/jobs/search/?f_C=1337&geoId=103644278&f_TPR=r2592000&f_SAL=f_SA_id_227001%3A278001%2C272003%2C279001%24f_SA_id_226001%3A272015&keywords=jobs',
           'https://www.linkedin.com/jobs/search/?f_C=1337&geoId=103644278'],
  'group': 'Big Tech'},
 {'name': 'Meta',
  'kind': 'meta',
  'slug': 'meta',
  'board': 'https://www.metacareers.com/jobsearch/?q=security',
  'group': 'Big Tech'},
 {'name': 'Microsoft',
  'kind': 'microsoft',
  'slug': 'microsoft',
  'board': 'https://apply.careers.microsoft.com/careers?query=Security&pid=1970393556942260&sort_by=relevance',
  'group': 'Big Tech'},
 {'name': 'Netflix',
  'kind': 'eightfold',
  'slug': 'netflix',
  'host': 'https://explore.jobs.netflix.net',
  'domain': 'netflix.com',
  'group': 'Big Tech'},
 {'name': 'NVIDIA',
  'kind': 'phenom',
  'slug': 'nvidia',
  'board': 'https://jobs.nvidia.com/careers?query=Security&pid=893394830937&sort_by=relevance',
  'search_url': 'https://jobs.nvidia.com/careers?query=Security&sort_by=relevance',
  'group': 'Big Tech'},
 {'name': 'Palantir', 'kind': 'lever', 'slug': 'palantir', 'group': 'Big Tech'},
 {'name': 'PayPal',
  'kind': 'workday',
  'slug': 'paypal',
  'board': 'https://paypal.wd1.myworkdayjobs.com/jobs',
  'group': 'Big Tech'},
 {'name': 'Pinterest', 'kind': 'greenhouse', 'slug': 'pinterest', 'group': 'Big Tech'},
 {'name': 'Proton', 'kind': 'greenhouse', 'slug': 'proton', 'board': 'https://proton.me/careers', 'group': 'Big Tech'},
 {'name': 'Qualcomm',
  'kind': 'phenom',
  'slug': 'qualcomm',
  'board': 'https://careers.qualcomm.com/careers',
  'search_url': 'https://careers.qualcomm.com/careers?query=security&sort_by=relevance',
  'group': 'Big Tech'},
 {'name': 'Robinhood', 'kind': 'greenhouse', 'slug': 'robinhood', 'group': 'Big Tech'},
 {'name': 'Roblox', 'kind': 'greenhouse', 'slug': 'roblox', 'group': 'Big Tech'},
 {'name': 'Salesforce',
  'kind': 'workday',
  'slug': 'salesforce',
  'board': 'https://salesforce.wd12.myworkdayjobs.com/External_Career_Site',
  'group': 'Big Tech'},
 {'name': 'SAP',
  'kind': 'pw',
  'slug': 'sap',
  'board': 'https://jobs.sap.com/search/?q=&locationsearch=&searchResultView=LIST',
  'search_url': 'https://jobs.sap.com/search/?q=&locationsearch=&searchResultView=LIST',
  'link_re': 'href="(/en/jobs/\\d+/[^"#?]+)"',
  'origin': 'https://jobs.sap.com',
  'group': 'Big Tech'},
 {'name': 'Stripe', 'kind': 'greenhouse', 'slug': 'stripe', 'group': 'Big Tech'},
 {'name': 'Twilio', 'kind': 'greenhouse', 'slug': 'twilio', 'group': 'Big Tech'},
 {'name': 'Unity',
  'kind': 'workday',
  'slug': 'unity',
  'board': 'https://unitytech.wd1.myworkdayjobs.com/Unity',
  'group': 'Big Tech'},
 {'name': 'VMware (Broadcom)',
  'kind': 'workday',
  'slug': 'broadcom',
  'board': 'https://broadcom.wd1.myworkdayjobs.com/External_Career',
  'group': 'Big Tech'},
 {'name': 'Anthropic', 'kind': 'greenhouse', 'slug': 'anthropic', 'group': 'Major AI Companies'},
 {'name': 'Cohere', 'kind': 'ashby', 'slug': 'cohere', 'group': 'Major AI Companies'},
 {'name': 'Cursor',
  'kind': 'ashby',
  'slug': 'cursor',
  'board': 'https://cursor.com/careers',
  'group': 'Major AI Companies'},
 {'name': 'DeepL', 'kind': 'ashby', 'slug': 'DeepL', 'group': 'Major AI Companies'},
 {'name': 'Eleven Labs', 'kind': 'ashby', 'slug': 'elevenlabs', 'group': 'Major AI Companies'},
 {'name': 'HF',
  'kind': 'workable',
  'slug': 'huggingface',
  'board': 'https://apply.workable.com/huggingface/',
  'group': 'Major AI Companies'},
 {'name': 'Mistral', 'kind': 'ashby', 'slug': 'mistral.ai', 'group': 'Major AI Companies'},
 {'name': 'OpenAI', 'kind': 'ashby', 'slug': 'openai', 'group': 'Major AI Companies'},
 {'name': 'Scale AI',
  'kind': 'scale',
  'slug': 'scale',
  'board': 'https://scale.com/careers',
  'search_url': 'https://scale.com/careers',
  'group': 'Major AI Companies'},
 {'name': 'Sony AI',
  'kind': 'pw',
  'slug': 'sonyai',
  'board': 'https://ai.sony/join-us',
  'search_url': 'https://ai.sony/join-us',
  'link_re': 'href="(https?://[^"]*(?:jobs|careers|job-postings|apply)[^"]*|/(?:jobs|careers|open-roles)/[^"#?]+)"',
  'origin': 'https://ai.sony',
  'group': 'Major AI Companies'},
 {'name': 'Ableton',
  'kind': 'ableton',
  'slug': 'ableton',
  'board': 'https://www.ableton.com/en/jobs/',
  'group': 'Music Companies'},
 {'name': 'Arturia',
  'kind': 'lucca',
  'slug': 'arturia-france',
  'board': 'https://jobs.world.luccasoftware.com/arturia-france',
  'group': 'Music Companies'},
 {'name': 'Avid',
  'kind': 'workday',
  'slug': 'avid',
  'board': 'https://avid.wd5.myworkdayjobs.com/AVID',
  'group': 'Music Companies'},
 {'name': 'Boris FX / iZotope',
  'kind': 'pw',
  'slug': 'borisfx',
  'board': 'https://borisfx.com/company/careers/',
  'search_url': 'https://borisfx.com/company/careers/',
  'link_re': 'href="(/company/careers/#[a-z0-9-]+)"',
  'origin': 'https://borisfx.com',
  'group': 'Music Companies'},
 {'name': 'Bose',
  'kind': 'bose',
  'slug': 'bose',
  'board': 'https://careers.bose.com/us/en',
  'search_url': 'https://careers.bose.com/us/en?query=&sort_by=relevance',
  'group': 'Music Companies'},
 {'name': 'Boss',
  'kind': 'boss',
  'slug': 'boss',
  'board': 'https://www.boss.info/uk/company/employment_opportunities/employment_opportunities/',
  'group': 'Music Companies'},
 {'name': 'Dolby',
  'kind': 'phenom',
  'slug': 'dolby',
  'board': 'https://jobs.dolby.com/careers',
  'search_url': 'https://jobs.dolby.com/careers?query=&sort_by=relevance',
  'group': 'Music Companies'},
 {'name': 'Elektron',
  'kind': 'teamtailor',
  'slug': 'elektron',
  'board': 'https://careers.elektron.se/jobs',
  'group': 'Music Companies'},
 {'name': 'Fender', 'kind': 'greenhouse', 'slug': 'fender', 'group': 'Music Companies'},
 {'name': 'inMusic Brands',
  'kind': 'pinpoint',
  'slug': 'inmusicbrands',
  'display_name': 'inMusic Brands (including Native Instruments)',
  'board': 'https://inmusicbrands.pinpointhq.com/',
  'group': 'Music Companies'},
 {'name': 'Marshall',
  'kind': 'teamtailor',
  'slug': 'marshall',
  'board': 'https://careers.marshall.com/jobs',
  'group': 'Music Companies'},
 {'name': 'MOTU',
  'kind': 'pw',
  'slug': 'motu',
  'board': 'https://motu.com/en-us/company/careers/',
  'search_url': 'https://motu.com/en-us/company/careers/',
  'link_re': 'href="(/en-us/company/careers/(?!$)[a-z0-9-]+/?)"',
  'origin': 'https://motu.com',
  'group': 'Music Companies'},
 {'name': 'Neural DSP',
  'kind': 'pw',
  'slug': 'neuraldsp',
  'board': 'https://careers.neuraldsp.com/',
  'search_url': 'https://revolutpeople.com/neural-dsp/public/careers/',
  'link_re': 'href="(/neural-dsp/public/careers/[^"#?]+|https?://revolutpeople\\.com/neural-dsp/public/careers/[^"#?]+)"',
  'origin': 'https://revolutpeople.com',
  'group': 'Music Companies'},
 {'name': 'Output', 'kind': 'ashby', 'slug': 'output', 'group': 'Music Companies'},
 {'name': 'Pioneer DJ', 'kind': 'ashby', 'slug': 'pioneer', 'group': 'Music Companies'},
 {'name': 'Roland',
  'kind': 'teamtailor',
  'slug': 'roland',
  'board': 'https://www.rolandcareers.com/jobs',
  'group': 'Music Companies'},
 {'name': 'Sennheiser',
  'kind': 'successfactors',
  'slug': 'sennheiser',
  'board': 'https://jobs.sennheiser.com/search/?q=&locationsearch=&locale=en_US&searchResultView=LIST',
  'group': 'Music Companies'},
 {'name': 'Seymour Duncan',
  'kind': 'pw',
  'slug': 'seymour',
  'board': 'https://www.seymourduncan.com/company/join-our-team',
  'search_url': 'https://www.seymourduncan.com/company/join-our-team',
  'link_re': 'href="(https?://yoursmartsource\\.hiringthing\\.com/job/\\d+/[a-z0-9-]+|https?://(?:www\\.)?seymourduncan\\.com/[a-z0-9-]+-job-posting|/[a-z0-9-]+-job-posting)"',
  'origin': 'https://www.seymourduncan.com',
  'group': 'Music Companies'},
 {'name': 'Slate Digital', 'kind': 'ashby', 'slug': 'slate', 'group': 'Music Companies'},
 {'name': 'Softube',
  'kind': 'bamboohr',
  'slug': 'softube',
  'board': 'https://softube.bamboohr.com/careers',
  'group': 'Music Companies'},
 {'name': 'Sonos',
  'kind': 'workday',
  'slug': 'sonos',
  'board': 'https://sonos.wd1.myworkdayjobs.com/Sonos',
  'group': 'Music Companies'},
 {'name': 'Spitfire Audio', 'kind': 'greenhouse', 'slug': 'spitfire', 'group': 'Music Companies'},
 {'name': 'Splice', 'kind': 'greenhouse', 'slug': 'splice', 'group': 'Music Companies'},
 {'name': 'Steinberg',
  'kind': 'pw',
  'slug': 'steinberg',
  'board': 'https://www.steinberg.net/careers/vacancies/',
  'search_url': 'https://www.steinberg.net/careers/vacancies/',
  'link_re': 'href="(https?://www\\.steinberg\\.net/careers/[^"#?]+|/careers/[^"#?/]+/[^"#?]+)"',
  'origin': 'https://www.steinberg.net',
  'group': 'Music Companies'},
 {'name': 'Suno', 'kind': 'ashby', 'slug': 'suno', 'group': 'Music Companies'},
 {'name': 'Udio', 'kind': 'greenhouse', 'slug': 'udio', 'group': 'Music Companies'},
 {'name': 'Universal Audio', 'kind': 'greenhouse', 'slug': 'universalaudio', 'group': 'Music Companies'},
 {'name': 'Yamaha',
  'kind': 'umantis',
  'slug': 'yamaha',
  'board': 'https://recruitingapp-5230.de.umantis.com/Jobs/All',
  'search_url': 'https://recruitingapp-5230.de.umantis.com/Jobs/All',
  'group': 'Music Companies'},
 {'name': 'Alan', 'kind': 'ashby', 'slug': 'alan', 'group': 'Other'},
 {'name': 'Brex', 'kind': 'greenhouse', 'slug': 'brex', 'group': 'Other'},
 {'name': 'Clay', 'kind': 'ashby', 'slug': 'clay', 'group': 'Other'},
 {'name': 'Clerk', 'kind': 'ashby', 'slug': 'clerk', 'group': 'Other'},
 {'name': 'Databricks', 'kind': 'greenhouse', 'slug': 'databricks', 'group': 'Other'},
 {'name': 'Datadog', 'kind': 'greenhouse', 'slug': 'datadog', 'group': 'Other'},
 {'name': 'Dataiku', 'kind': 'greenhouse', 'slug': 'dataiku', 'group': 'Other'},
 {'name': 'Doctolib', 'kind': 'ashby', 'slug': 'doctolib', 'group': 'Other'},
 {'name': 'Fastly', 'kind': 'greenhouse', 'slug': 'fastly', 'group': 'Other'},
 {'name': 'Figma', 'kind': 'greenhouse', 'slug': 'figma', 'group': 'Other'},
 {'name': 'GitLab', 'kind': 'greenhouse', 'slug': 'gitlab', 'group': 'Other'},
 {'name': 'Grafana Labs', 'kind': 'greenhouse', 'slug': 'grafanalabs', 'group': 'Other'},
 {'name': 'HashiCorp', 'kind': 'workable', 'slug': 'hashicorp', 'group': 'Other'},
 {'name': 'Hex', 'kind': 'ashby', 'slug': 'hex', 'group': 'Other'},
 {'name': 'Linear', 'kind': 'ashby', 'slug': 'linear', 'group': 'Other'},
 {'name': 'Mercury', 'kind': 'ashby', 'slug': 'mercury', 'group': 'Other'},
 {'name': 'Modern Treasury', 'kind': 'greenhouse', 'slug': 'moderntreasury', 'group': 'Other'},
 {'name': 'Notion', 'kind': 'greenhouse', 'slug': 'notion', 'group': 'Other'},
 {'name': 'Owkin', 'kind': 'ashby', 'slug': 'owkin', 'group': 'Other'},
 {'name': 'Qonto', 'kind': 'ashby', 'slug': 'qonto', 'group': 'Other'},
 {'name': 'Ramp', 'kind': 'greenhouse', 'slug': 'ramp', 'group': 'Other'},
 {'name': 'Retool', 'kind': 'greenhouse', 'slug': 'retool', 'group': 'Other'},
 {'name': 'Snowflake', 'kind': 'ashby', 'slug': 'snowflake', 'group': 'Other'},
 {'name': 'Supabase', 'kind': 'ashby', 'slug': 'supabase', 'group': 'Other'},
 {'name': 'Vercel', 'kind': 'greenhouse', 'slug': 'vercel', 'group': 'Other'},
 {'name': 'Welcome to the Jungle',
  'kind': 'wttj',
  'slug': 'wttj',
  'board': 'https://www.welcometothejungle.com/fr/jobs?query=security',
  'search_url': 'https://www.welcometothejungle.com/fr/jobs?query=security',
  'group': 'Other'},
 {'name': 'WorkOS', 'kind': 'ashby', 'slug': 'workos', 'group': 'Other'},
 {'name': 'Zapier', 'kind': 'greenhouse', 'slug': 'zapier', 'group': 'Other'},
 {'name': '1Password', 'kind': 'ashby', 'slug': '1password', 'group': 'Security Companies'},
 {'name': 'Aisle',
  'kind': 'ashby',
  'slug': 'aisle',
  'board': 'https://aisle.com/careers',
  'group': 'Security Companies'},
 {'name': 'BeyondTrust', 'kind': 'greenhouse', 'slug': 'beyondtrust', 'group': 'Security Companies'},
 {'name': 'Bitwarden', 'kind': 'greenhouse', 'slug': 'bitwarden', 'group': 'Security Companies'},
 {'name': 'Cape Privacy', 'kind': 'ashby', 'slug': 'cape', 'group': 'Security Companies'},
 {'name': 'Chainguard', 'kind': 'greenhouse', 'slug': 'chainguard', 'group': 'Security Companies'},
 {'name': 'Checkmarx',
  'kind': 'checkmarx',
  'slug': 'checkmarx',
  'board': 'https://checkmarx.com/company/careers/',
  'search_url': 'https://checkmarx.com/company/careers/',
  'group': 'Security Companies'},
 {'name': 'Cloudflare', 'kind': 'greenhouse', 'slug': 'cloudflare', 'group': 'Security Companies'},
 {'name': 'Corgea',
  'kind': 'pw',
  'slug': 'corgea',
  'board': 'https://www.ycombinator.com/companies/corgea/jobs',
  'search_url': 'https://www.ycombinator.com/companies/corgea/jobs',
  'link_re': 'href="(/companies/corgea/jobs/[^"#?]+)"',
  'origin': 'https://www.ycombinator.com',
  'group': 'Security Companies'},
 {'name': 'CrowdStrike',
  'kind': 'pw',
  'slug': 'crowdstrike',
  'board': 'https://crowdstrike.wd5.myworkdayjobs.com/en-US/crowdstrikecareers?q=security',
  'search_url': 'https://crowdstrike.wd5.myworkdayjobs.com/en-US/crowdstrikecareers?q=security',
  'link_re': 'href="(/en-US/crowdstrikecareers/job/[^"]+)"',
  'origin': 'https://crowdstrike.wd5.myworkdayjobs.com',
  'wait_selector': "a[href*='/crowdstrikecareers/job/']",
  'group': 'Security Companies'},
 {'name': 'Cybereason', 'kind': 'greenhouse', 'slug': 'cybereason', 'group': 'Security Companies'},
 {'name': 'DepthFirst', 'kind': 'ashby', 'slug': 'depthfirst', 'group': 'Security Companies'},
 {'name': 'Doppler', 'kind': 'ashby', 'slug': 'doppler', 'group': 'Security Companies'},
 {'name': 'Elastic', 'kind': 'greenhouse', 'slug': 'elastic', 'group': 'Security Companies'},
 {'name': 'Endor Labs', 'kind': 'greenhouse', 'slug': 'endorlabs', 'group': 'Security Companies'},
 {'name': 'GitGuardian',
  'kind': 'pw',
  'slug': 'gitguardian',
  'board': 'https://www.gitguardian.com/careers',
  'search_url': 'https://www.gitguardian.com/careers',
  'link_re': 'href="(/job-openings/\\d+-[a-z0-9-]+)"',
  'origin': 'https://www.gitguardian.com',
  'group': 'Security Companies'},
 {'name': 'Netskope', 'kind': 'greenhouse', 'slug': 'netskope', 'group': 'Security Companies'},
 {'name': 'Nord Security', 'kind': 'ashby', 'slug': 'nord-security', 'group': 'Security Companies'},
 {'name': 'Okta', 'kind': 'greenhouse', 'slug': 'okta', 'group': 'Security Companies'},
 {'name': 'Pixee',
  'kind': 'pixee',
  'slug': 'pixee',
  'board': 'https://app.dover.com/jobs/pixee',
  'search_url': 'https://app.dover.com/jobs/pixee',
  'group': 'Security Companies'},
 {'name': 'PQShield', 'kind': 'greenhouse', 'slug': 'pqshield', 'group': 'Security Companies'},
 {'name': 'SandboxAQ', 'kind': 'ashby', 'slug': 'sandboxaq', 'group': 'Security Companies'},
 {'name': 'Secureframe', 'kind': 'greenhouse', 'slug': 'secureframe', 'group': 'Security Companies'},
 {'name': 'Semgrep',
  'kind': 'pw',
  'slug': 'semgrep',
  'board': 'https://semgrep.dev/about/careers/',
  'search_url': 'https://semgrep.dev/about/careers/',
  'link_re': 'href="(https?://[^"]*greenhouse[^"]*/semgrep/jobs/\\d+[^"]*|/about/careers/[^"#?/]+/?)"',
  'origin': 'https://semgrep.dev',
  'wait_selector': "a[href*='/jobs/'], a[href*='/careers/']",
  'group': 'Security Companies'},
 {'name': 'Snyk', 'kind': 'ashby', 'slug': 'snyk', 'group': 'Security Companies'},
 {'name': 'Socket', 'kind': 'ashby', 'slug': 'socket', 'group': 'Security Companies'},
 {'name': 'Tailscale', 'kind': 'greenhouse', 'slug': 'tailscale', 'group': 'Security Companies'},
 {'name': 'Wiz', 'kind': 'ashby', 'slug': 'wiz', 'group': 'Security Companies'},
 {'name': 'XBOW', 'kind': 'ashby', 'slug': 'xbowcareers', 'group': 'Security Companies'},
 {'name': 'Yubico', 'kind': 'greenhouse', 'slug': 'yubico', 'group': 'Security Companies'},
 {'name': 'ZeroPath',
  'kind': 'pw',
  'slug': 'zeropath',
  'board': 'https://zeropath.com/careers',
  'search_url': 'https://zeropath.com/careers',
  'link_re': 'href="(https?://jobs\\.ashbyhq\\.com/[^"#?]+/[a-f0-9-]{20,}|/careers/[^"#?]+|https?://[^"]*(?:greenhouse|lever|workable|ashby)[^"]*)"',
  'origin': 'https://zeropath.com',
  'group': 'Security Companies'}]
